Assignment2/Assignment_2_WDT/Assignment_2_WDT/Models/UserGame.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment_2_WDT.Models
{
    using System;
    using System.Collections.Generic;
    using System.Text.RegularExpressions;

    public partial class UserGame
    {
        private string userID;

        public UserGame(string userID, string name, int height, int width, string cells)
        {
            this.userID = userID;
            Name = name;
            Height = height;
            Width = width;
            Cells = cells;
        }

        public UserGame(int userGameID, string userID, string name, int height, int width, string cells)
        {
            UserGameID = userGameID;
            this.userID = userID;
            Name = name;
            Height = height;
            Width = width;
            Cells = cells;
        }

        public int UserGameID { get; set; }
        public int UserID { get; set; }
        public string Name { get; set; }
        public int Height { get; set; }
        public int Width { get; set; }
        public string Cells { get; set; }

        public virtual User User { get; set; }

        // this method is used to display the Cells as unicode characters instead of the XO string
        public string convertCells
        {
            get
            {
                string cellarray = Cells;
                int height = Height;
                int width = Width;
                string name = Name;
                string output = "";

                string[] CellsArray = cellarray.Split(new string[] { "\n", "\r\n" }, StringSplitOptions.RemoveEmptyEntries);
                int Count = height;
                Regex XOxo = new Regex(@"^[XxOo]+$");
                char[][] JAState = new char[height][];
                for (int i = 0; i < height; i++)
                {
                    JAState[i] = CellsArray[i].ToCharArray();
                }
                
                for (int i = 0; i < JAState.Length; i++)
                {
                    char[] innerArray = JAState[i];
                    for (int a = 0; a < innerArray.Length; a++)
                    {
                        if ((innerArray[a] == 'x') || (innerArray[a] == 'X')) { JAState[i][a] = ' '; }
                        if ((innerArray[a] == 'o') || (innerArray[a] == 'O')) { JAState[i][a] = Globals.aliveCellChar; }
                        output += JAState[i][a].ToString();
                    }
                    output += Environment.NewLine;
                }

                return (output);
            }

        }
    }
}

Assignment2/Assignment_2_WDT/Assignment_2_WDT/Controllers/UserGamesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Assignment_2_WDT.Models;
using Assignment_2_WDT.Attributes;

namespace Assignment_2_WDT.Controllers
{
    public class UserGamesController : Controller
    {
        private A2WDTDBEntities1 db = new A2WDTDBEntities1();

        public ActionResult ActiveGames()
        {
            var gm = (List<GameOfLife>)Session["ActiveGames"];
            GameOfLife[] games = gm.ToArray();
            ViewData["Games"] = games;
            return View();
        }

        public ActionResult SaveGame()
        {
            GameOfLife game = (GameOfLife)Session["GameOfLife"];
            string UserID = Session["UserID"].ToString();
            string Name = Session["Name"].ToString();
            int Height = game.Height;
            int Width = game.Width;
            string Cells = game.ToPlainString();
            UserGame last = db.UserGames.Last();
            int newID = last.UserGameID + 1;
            UserGame userGame = new UserGame(newID, UserID, Name, Height, Width, Cells);
            if (ModelState.IsValid)
            {
                db.UserGames.Add(userGame);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }

        //GET: Start the game already !
        public Object PlayGame()
        {

            GameOfLife gameOfLife = (GameOfLife)Session["GameOfLife"];
            string convertedCells = gameOfLife.ToString();
            ViewData["Cells"] = convertedCells;
            return View();
        }

        public ActionResult PlayActiveGame(GameOfLife game)
        {
            Session["GameOfLife"] = game;
            string convertedCells = game.ToString();
            ViewData["Cells"] = convertedCells;
            return View();
        }

        //GET: Start the game already !
        public Object takeTurn()
        {
            GameOfLife gameOfLife = (GameOfLife)Session["GameOfLife"];
            gameOfLife.TakeTurn();
            return gameOfLife;
        }


        // GET: UserGames
        public ActionResult Index()
        {
            var userGames = db.UserGames.Include(u => u.User);
            return View(userGames.ToList());
        }

        // GET: UserGames/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserGame userGame = db.UserGames.Find(id);
            if (userGame == null)
            {
                return HttpNotFound();
            }
            return View(userGame);
        }

        // GET: UserGames/Create
        public ActionResult Create()
        {
            ViewBag.UserID = new SelectList(db.User, "UserID", "Email");
            return View();
        }

        // POST: UserGames/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "UserGameID,UserID,Name,Height,Width,Cells")] UserGame userGame)
        {
            if (ModelState.IsValid)
            {
                db.UserGames.Add(userGame);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.UserID = new SelectList(db.User, "UserID", "Email", userGame.UserID);
            return View(userGame);
        }

        // GET: UserGames/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserGame userGame = db.UserGames.Find(id);
            if (userGame == null)
            {
                return HttpNotFound();
            }
            ViewBag.UserID = new SelectList(db.User, "UserID", "Email", userGame.UserID);
            return View(userGame);
        }

        // POST: UserGames/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "UserGameID,UserID,Name,Height,Width,Cells")] UserGame userGame)
        {
            if (ModelState.IsValid)
            {
                db.Entry(userGame).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.UserID = new SelectList(db.User, "UserID", "Email", userGame.UserID);
            return View(userGame);
        }

        // GET: UserGames/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserGame userGame = db.UserGames.Find(id);
            if (userGame == null)
            {
                return HttpNotFound();
            }
            return View(userGame);
        }

        // POST: UserGames/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            UserGame userGame = db.UserGames.Find(id);
            db.UserGames.Remove(userGame);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Assignment2/Assignment_2_WDT/Assignment_2_WDT/Views/UserGames/ActiveGames.cshtml
@{
    ViewBag.Title = "ActiveGames";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@{
    GameOfLife[] games = (GameOfLife[])ViewData["Games"];
}
<h2>ActiveGames</h2>
<div>
    <table class="table">

        <tr>
            <th>
                Name
            </th>
            <th>
                Height
            </th>
            <th>
                Width
            </th>
            <th>
                Cells
            </th>

            <th></th>
        </tr>

        @for (int i = 0; i < games.Length; i++)
            {

            <tr>
                <td>
                    Name: @games[i].Name
                </td>
                <td>
                    Height: @games[i].Height
                </td>

                <td>
                    Width: @games[i].Width
                </td>
                <td>
                    <pre>@games[i].ToString()</pre>
                </td>

                <td>
                    @Html.ActionLink("Playgame", "PlayActiveGame", games[i]) |
                    @Html.ActionLink("Delete", "Delete", new { id = i })

                </td>
            </tr>


        }
    </table>
</div>

Assignment2/Assignment_2_WDT/Assignment_2_WDT/Views/UserGames/Create.cshtml
@model Assignment_2_WDT.Models.UserGame

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>UserGame</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.UserID, "UserID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("UserID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UserID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Height, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Height, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Height, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Width, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Width, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Width, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cells, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cells, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cells, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Assignment2/Assignment_2_WDT/Assignment_2_WDT/Views/UserGames/Delete.cshtml
@model Assignment_2_WDT.Models.UserGame

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>UserGame</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Height)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Height)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Width)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Width)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cells)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cells)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.User.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.Email)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Assignment2/Assignment_2_WDT/Assignment_2_WDT/Views/UserGames/Details.cshtml
@model Assignment_2_WDT.Models.UserGame

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>UserGame</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Height)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Height)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Width)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Width)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cells)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cells)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.User.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.Email)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.UserGameID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Assignment2/Assignment_2_WDT/Assignment_2_WDT/Views/UserGames/Edit.cshtml
@model Assignment_2_WDT.Models.UserGame

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>UserGame</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.UserGameID)

        <div class="form-group">
            @Html.LabelFor(model => model.UserID, "UserID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("UserID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UserID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Height, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Height, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Height, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Width, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Width, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Width, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cells, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cells, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cells, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Assignment2/Assignment_2_WDT/Assignment_2_WDT/Views/UserGames/Index.cshtml
@model IEnumerable<Assignment_2_WDT.Models.UserGame>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Height)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Width)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Cells)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.User.Email)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Height)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Width)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Cells)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.User.Email)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.UserGameID }) |
            @Html.ActionLink("Details", "Details", new { id=item.UserGameID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.UserGameID })
        </td>
    </tr>
}

</table>

Assignment2/Assignment_2_WDT/Assignment_2_WDT/Views/UserGames/PlayGame.cshtml
@model Object

@{
    ViewBag.Title = "Play Game";
}

<h2>Game!</h2>
@{
    var cells = ViewData["Cells"];
}
<div>

    <hr />
    <dl class="dl-horizontal">
        <dt>State</dt>
        <dd>
            <pre id="state">@cells.ToString()</pre>
        </dd>

        <dt></dt>
        <dd>
            <button class="btn btn-primary btn-lg" id="playGame">Play Game</button>
            <br /><br />
            <button class="btn btn-primary btn-lg" id="stopGame" disabled>Stop Game</button>
            <br /><br />
            <input type="button" class="btn btn-primary btn-lg" value="Save Game" onclick="location.href='@Url.Action("SaveGame", "UserGames")'" />
            <br /><br />
        </dd>
    </dl>
</div>

<script>
    $(document).ready(function()
    {
        var playGameButton = $("#playGame");
        var stopGameButton = $("#stopGame");

        // ReSharper disable once InconsistentNaming
        var intervalID;

        playGameButton.click(function()
        {
            playGameButton.prop("disabled", true);
            stopGameButton.prop("disabled", false);

            intervalID = setInterval(function()
            {
                $.post("@Url.Action("TakeTurn")", function(data)
                {
                    $("#state").html(data);
                });
            }, 1000);
        });

        $("#stopGame").click(function()
        {
            playGameButton.prop("disabled", false);
            stopGameButton.prop("disabled", true);

            clearInterval(intervalID);
        });
    });
</script>